Use a dedicated user running crafter
Some crafter components require a writable HOME directory.

The `daemon` user has its HOME directory set to `/usr/sbin` which is not
writable for the user itself causing an error:

```
Exception
org.craftercms.engine.exception.SiteContextCreationException: Unable to load application context for site 'thalia-crafter-site'

Root Cause
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
General error during conversion: Error grabbing grapes -- /usr/sbin/.groovy/grapes/resolved-caller-all-caller-working43.xml (No such file or directory).
```

This change updates the `crafter-jre` base image such that `/opt/crafter` is the
HOME of the `crafter` user. And it uses an entrypoint script that changes the
owner of all files in `/opt/crafter/data` to be owned by the `crafter user when
staring up.

The `Dockerfiles` and `supervisor.conf` files are adapted to use the new user
when running the services.